import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Navbar from "./components/Navbar";
import { Grid, GridItem } from "@chakra-ui/react";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Grid
            p="2"
            gap="4"
            h="100vh"
            templateAreas={`"header header"
          "nav main"`}
            gridTemplateRows={"60px 1fr"}
            gridTemplateColumns={"auto 1fr"}
          >
            <GridItem area={"header"}>
              <Header />
            </GridItem>
            <GridItem area={"nav"}>
              <Navbar />
            </GridItem>
            <GridItem area={"main"}>
              {children}
            </GridItem>
          </Grid>
        </Providers>
      </body>
    </html>
  );
}
